name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  org:
    description: The org to use for the action
    default: ${{ github.event.organization.login }}
    required: false
  repo:
    description: The repo to use for the action
    default: ${{ github.event.repository.name }}
    required: false
  file:
    description: The yaml file containing a list of repos
    default: repos.yml
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
