name: 'ghas-rollout-compliance-action'
author: 'NickLiffen'
description: 'A GitHub Action that helps organisations roll out GHAS in a controlled and structured fashion'
inputs:
  reposApprovedToUseGHASFile:
    description: 'The file location of the file which contains the repos that can use GHAS'
    required: true
outputs:
  success:
    description: 'Wether or not the action ran successfully'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'target'  
  color: 'blue'